/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetReadDto
 */
export interface AssetReadDto {
    /**
     * 
     * @type {string}
     * @memberof AssetReadDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetReadDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetReadDto
     */
    mime?: string;
    /**
     * 
     * @type {number}
     * @memberof AssetReadDto
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof AssetReadDto
     */
    url?: string;
}

/**
 * Check if a given object implements the AssetReadDto interface.
 */
export function instanceOfAssetReadDto(value: object): boolean {
    return true;
}

export function AssetReadDtoFromJSON(json: any): AssetReadDto {
    return AssetReadDtoFromJSONTyped(json, false);
}

export function AssetReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetReadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'mime': json['mime'] == null ? undefined : json['mime'],
        'size': json['size'] == null ? undefined : json['size'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function AssetReadDtoToJSON(value?: AssetReadDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'mime': value['mime'],
        'size': value['size'],
        'url': value['url'],
    };
}

