/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Asset
 */
export interface Asset {
    /**
     * 
     * @type {string}
     * @memberof Asset
     */
    assetId: string;
    /**
     * 
     * @type {string}
     * @memberof Asset
     */
    assetName: string;
    /**
     * 
     * @type {string}
     * @memberof Asset
     */
    assetPath: string;
    /**
     * 
     * @type {string}
     * @memberof Asset
     */
    assetMime?: string;
    /**
     * 
     * @type {number}
     * @memberof Asset
     */
    size?: number;
}

/**
 * Check if a given object implements the Asset interface.
 */
export function instanceOfAsset(value: object): boolean {
    if (!('assetId' in value)) return false;
    if (!('assetName' in value)) return false;
    if (!('assetPath' in value)) return false;
    return true;
}

export function AssetFromJSON(json: any): Asset {
    return AssetFromJSONTyped(json, false);
}

export function AssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Asset {
    if (json == null) {
        return json;
    }
    return {
        
        'assetId': json['assetId'],
        'assetName': json['assetName'],
        'assetPath': json['assetPath'],
        'assetMime': json['assetMime'] == null ? undefined : json['assetMime'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function AssetToJSON(value?: Asset | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'assetId': value['assetId'],
        'assetName': value['assetName'],
        'assetPath': value['assetPath'],
        'assetMime': value['assetMime'],
        'size': value['size'],
    };
}

