/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CircleWebsiteReadDto
 */
export interface CircleWebsiteReadDto {
    /**
     * 
     * @type {string}
     * @memberof CircleWebsiteReadDto
     */
    url?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CircleWebsiteReadDto
     */
    invalid?: boolean;
}

/**
 * Check if a given object implements the CircleWebsiteReadDto interface.
 */
export function instanceOfCircleWebsiteReadDto(value: object): boolean {
    return true;
}

export function CircleWebsiteReadDtoFromJSON(json: any): CircleWebsiteReadDto {
    return CircleWebsiteReadDtoFromJSONTyped(json, false);
}

export function CircleWebsiteReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CircleWebsiteReadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'invalid': json['invalid'] == null ? undefined : json['invalid'],
    };
}

export function CircleWebsiteReadDtoToJSON(value?: CircleWebsiteReadDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'invalid': value['invalid'],
    };
}

