/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CircleWriteDto
 */
export interface CircleWriteDto {
    /**
     * 
     * @type {string}
     * @memberof CircleWriteDto
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CircleWriteDto
     */
    alias?: Array<string>;
}

/**
 * Check if a given object implements the CircleWriteDto interface.
 */
export function instanceOfCircleWriteDto(value: object): boolean {
    return true;
}

export function CircleWriteDtoFromJSON(json: any): CircleWriteDto {
    return CircleWriteDtoFromJSONTyped(json, false);
}

export function CircleWriteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CircleWriteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'alias': json['alias'] == null ? undefined : json['alias'],
    };
}

export function CircleWriteDtoToJSON(value?: CircleWriteDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'alias': value['alias'],
    };
}

