/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HlsSegmentWriteDto
 */
export interface HlsSegmentWriteDto {
    /**
     * 
     * @type {string}
     * @memberof HlsSegmentWriteDto
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof HlsSegmentWriteDto
     */
    index?: number;
    /**
     * 
     * @type {string}
     * @memberof HlsSegmentWriteDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof HlsSegmentWriteDto
     */
    hlsSegmentPath?: string;
    /**
     * 
     * @type {string}
     * @memberof HlsSegmentWriteDto
     */
    hlsPlaylistId?: string;
}

/**
 * Check if a given object implements the HlsSegmentWriteDto interface.
 */
export function instanceOfHlsSegmentWriteDto(value: object): boolean {
    return true;
}

export function HlsSegmentWriteDtoFromJSON(json: any): HlsSegmentWriteDto {
    return HlsSegmentWriteDtoFromJSONTyped(json, false);
}

export function HlsSegmentWriteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HlsSegmentWriteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'index': json['index'] == null ? undefined : json['index'],
        'name': json['name'] == null ? undefined : json['name'],
        'hlsSegmentPath': json['hlsSegmentPath'] == null ? undefined : json['hlsSegmentPath'],
        'hlsPlaylistId': json['hlsPlaylistId'] == null ? undefined : json['hlsPlaylistId'],
    };
}

export function HlsSegmentWriteDtoToJSON(value?: HlsSegmentWriteDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'index': value['index'],
        'name': value['name'],
        'hlsSegmentPath': value['hlsSegmentPath'],
        'hlsPlaylistId': value['hlsPlaylistId'],
    };
}

