/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocalizedField
 */
export interface LocalizedField {
    /**
     * 
     * @type {string}
     * @memberof LocalizedField
     */
    _default: string;
    /**
     * 
     * @type {string}
     * @memberof LocalizedField
     */
    en?: string;
    /**
     * 
     * @type {string}
     * @memberof LocalizedField
     */
    zh?: string;
    /**
     * 
     * @type {string}
     * @memberof LocalizedField
     */
    jp?: string;
}

/**
 * Check if a given object implements the LocalizedField interface.
 */
export function instanceOfLocalizedField(value: object): boolean {
    if (!('_default' in value)) return false;
    return true;
}

export function LocalizedFieldFromJSON(json: any): LocalizedField {
    return LocalizedFieldFromJSONTyped(json, false);
}

export function LocalizedFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedField {
    if (json == null) {
        return json;
    }
    return {
        
        '_default': json['default'],
        'en': json['en'] == null ? undefined : json['en'],
        'zh': json['zh'] == null ? undefined : json['zh'],
        'jp': json['jp'] == null ? undefined : json['jp'],
    };
}

export function LocalizedFieldToJSON(value?: LocalizedField | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'default': value['_default'],
        'en': value['en'],
        'zh': value['zh'],
        'jp': value['jp'],
    };
}

