/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Operation
 */
export interface Operation {
    /**
     * 
     * @type {any}
     * @memberof Operation
     */
    value?: any;
    /**
     * 
     * @type {string}
     * @memberof Operation
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof Operation
     */
    op?: string;
    /**
     * 
     * @type {string}
     * @memberof Operation
     */
    from?: string;
}

/**
 * Check if a given object implements the Operation interface.
 */
export function instanceOfOperation(value: object): boolean {
    return true;
}

export function OperationFromJSON(json: any): Operation {
    return OperationFromJSONTyped(json, false);
}

export function OperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Operation {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
        'path': json['path'] == null ? undefined : json['path'],
        'op': json['op'] == null ? undefined : json['op'],
        'from': json['from'] == null ? undefined : json['from'],
    };
}

export function OperationToJSON(value?: Operation | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'value': value['value'],
        'path': value['path'],
        'op': value['op'],
        'from': value['from'],
    };
}

