/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OperationType = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6
} as const;
export type OperationType = typeof OperationType[keyof typeof OperationType];


export function OperationTypeFromJSON(json: any): OperationType {
    return OperationTypeFromJSONTyped(json, false);
}

export function OperationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationType {
    return json as OperationType;
}

export function OperationTypeToJSON(value?: OperationType | null): any {
    return value as any;
}

