/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LocalizedField } from './LocalizedField';
import {
    LocalizedFieldFromJSON,
    LocalizedFieldFromJSONTyped,
    LocalizedFieldToJSON,
} from './LocalizedField';

/**
 * 
 * @export
 * @interface OriginalTrackWriteDto
 */
export interface OriginalTrackWriteDto {
    /**
     * 
     * @type {string}
     * @memberof OriginalTrackWriteDto
     */
    id: string;
    /**
     * 
     * @type {LocalizedField}
     * @memberof OriginalTrackWriteDto
     */
    title: LocalizedField;
    /**
     * 
     * @type {string}
     * @memberof OriginalTrackWriteDto
     */
    externalReference?: string;
}

/**
 * Check if a given object implements the OriginalTrackWriteDto interface.
 */
export function instanceOfOriginalTrackWriteDto(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('title' in value)) return false;
    return true;
}

export function OriginalTrackWriteDtoFromJSON(json: any): OriginalTrackWriteDto {
    return OriginalTrackWriteDtoFromJSONTyped(json, false);
}

export function OriginalTrackWriteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OriginalTrackWriteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': LocalizedFieldFromJSON(json['title']),
        'externalReference': json['externalReference'] == null ? undefined : json['externalReference'],
    };
}

export function OriginalTrackWriteDtoToJSON(value?: OriginalTrackWriteDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': LocalizedFieldToJSON(value['title']),
        'externalReference': value['externalReference'],
    };
}

