/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LocalizedField } from './LocalizedField';
import {
    LocalizedFieldFromJSON,
    LocalizedFieldFromJSONTyped,
    LocalizedFieldToJSON,
} from './LocalizedField';

/**
 * 
 * @export
 * @interface OriginalAlbumReadDto
 */
export interface OriginalAlbumReadDto {
    /**
     * 
     * @type {string}
     * @memberof OriginalAlbumReadDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OriginalAlbumReadDto
     */
    type?: string;
    /**
     * 
     * @type {LocalizedField}
     * @memberof OriginalAlbumReadDto
     */
    fullName?: LocalizedField;
    /**
     * 
     * @type {LocalizedField}
     * @memberof OriginalAlbumReadDto
     */
    shortName?: LocalizedField;
}

/**
 * Check if a given object implements the OriginalAlbumReadDto interface.
 */
export function instanceOfOriginalAlbumReadDto(value: object): boolean {
    return true;
}

export function OriginalAlbumReadDtoFromJSON(json: any): OriginalAlbumReadDto {
    return OriginalAlbumReadDtoFromJSONTyped(json, false);
}

export function OriginalAlbumReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OriginalAlbumReadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'fullName': json['fullName'] == null ? undefined : LocalizedFieldFromJSON(json['fullName']),
        'shortName': json['shortName'] == null ? undefined : LocalizedFieldFromJSON(json['shortName']),
    };
}

export function OriginalAlbumReadDtoToJSON(value?: OriginalAlbumReadDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'type': value['type'],
        'fullName': LocalizedFieldToJSON(value['fullName']),
        'shortName': LocalizedFieldToJSON(value['shortName']),
    };
}

