/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LocalizedField } from './LocalizedField';
import {
    LocalizedFieldFromJSON,
    LocalizedFieldFromJSONTyped,
    LocalizedFieldToJSON,
} from './LocalizedField';
import type { OriginalAlbumReadDto } from './OriginalAlbumReadDto';
import {
    OriginalAlbumReadDtoFromJSON,
    OriginalAlbumReadDtoFromJSONTyped,
    OriginalAlbumReadDtoToJSON,
} from './OriginalAlbumReadDto';

/**
 * 
 * @export
 * @interface OriginalTrackReadDto
 */
export interface OriginalTrackReadDto {
    /**
     * 
     * @type {string}
     * @memberof OriginalTrackReadDto
     */
    id?: string;
    /**
     * 
     * @type {LocalizedField}
     * @memberof OriginalTrackReadDto
     */
    title?: LocalizedField;
    /**
     * 
     * @type {OriginalAlbumReadDto}
     * @memberof OriginalTrackReadDto
     */
    album?: OriginalAlbumReadDto;
}

/**
 * Check if a given object implements the OriginalTrackReadDto interface.
 */
export function instanceOfOriginalTrackReadDto(value: object): boolean {
    return true;
}

export function OriginalTrackReadDtoFromJSON(json: any): OriginalTrackReadDto {
    return OriginalTrackReadDtoFromJSONTyped(json, false);
}

export function OriginalTrackReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OriginalTrackReadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : LocalizedFieldFromJSON(json['title']),
        'album': json['album'] == null ? undefined : OriginalAlbumReadDtoFromJSON(json['album']),
    };
}

export function OriginalTrackReadDtoToJSON(value?: OriginalTrackReadDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': LocalizedFieldToJSON(value['title']),
        'album': OriginalAlbumReadDtoToJSON(value['album']),
    };
}

