/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaylistType } from './PlaylistType';
import {
    PlaylistTypeFromJSON,
    PlaylistTypeFromJSONTyped,
    PlaylistTypeToJSON,
} from './PlaylistType';
import type { PlaylistVisibility } from './PlaylistVisibility';
import {
    PlaylistVisibilityFromJSON,
    PlaylistVisibilityFromJSONTyped,
    PlaylistVisibilityToJSON,
} from './PlaylistVisibility';
import type { UserProfile } from './UserProfile';
import {
    UserProfileFromJSON,
    UserProfileFromJSONTyped,
    UserProfileToJSON,
} from './UserProfile';

/**
 * 
 * @export
 * @interface PlaylistReadDto
 */
export interface PlaylistReadDto {
    /**
     * 
     * @type {string}
     * @memberof PlaylistReadDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistReadDto
     */
    name?: string;
    /**
     * 
     * @type {UserProfile}
     * @memberof PlaylistReadDto
     */
    owner?: UserProfile;
    /**
     * 
     * @type {PlaylistVisibility}
     * @memberof PlaylistReadDto
     */
    visibility?: PlaylistVisibility;
    /**
     * 
     * @type {PlaylistType}
     * @memberof PlaylistReadDto
     */
    type?: PlaylistType;
    /**
     * 
     * @type {Date}
     * @memberof PlaylistReadDto
     */
    lastModified?: Date;
}

/**
 * Check if a given object implements the PlaylistReadDto interface.
 */
export function instanceOfPlaylistReadDto(value: object): boolean {
    return true;
}

export function PlaylistReadDtoFromJSON(json: any): PlaylistReadDto {
    return PlaylistReadDtoFromJSONTyped(json, false);
}

export function PlaylistReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaylistReadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'owner': json['owner'] == null ? undefined : UserProfileFromJSON(json['owner']),
        'visibility': json['visibility'] == null ? undefined : PlaylistVisibilityFromJSON(json['visibility']),
        'type': json['type'] == null ? undefined : PlaylistTypeFromJSON(json['type']),
        'lastModified': json['lastModified'] == null ? undefined : (new Date(json['lastModified'])),
    };
}

export function PlaylistReadDtoToJSON(value?: PlaylistReadDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'owner': UserProfileToJSON(value['owner']),
        'visibility': PlaylistVisibilityToJSON(value['visibility']),
        'type': PlaylistTypeToJSON(value['type']),
        'lastModified': value['lastModified'] == null ? undefined : ((value['lastModified']).toISOString()),
    };
}

