/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaylistVisibility } from './PlaylistVisibility';
import {
    PlaylistVisibilityFromJSON,
    PlaylistVisibilityFromJSONTyped,
    PlaylistVisibilityToJSON,
} from './PlaylistVisibility';

/**
 * 
 * @export
 * @interface PlaylistInfo
 */
export interface PlaylistInfo {
    /**
     * 
     * @type {string}
     * @memberof PlaylistInfo
     */
    name?: string;
    /**
     * 
     * @type {PlaylistVisibility}
     * @memberof PlaylistInfo
     */
    visibility?: PlaylistVisibility;
}

/**
 * Check if a given object implements the PlaylistInfo interface.
 */
export function instanceOfPlaylistInfo(value: object): boolean {
    return true;
}

export function PlaylistInfoFromJSON(json: any): PlaylistInfo {
    return PlaylistInfoFromJSONTyped(json, false);
}

export function PlaylistInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaylistInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'visibility': json['visibility'] == null ? undefined : PlaylistVisibilityFromJSON(json['visibility']),
    };
}

export function PlaylistInfoToJSON(value?: PlaylistInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'visibility': PlaylistVisibilityToJSON(value['visibility']),
    };
}

