/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaylistItemReadDto
 */
export interface PlaylistItemReadDto {
    /**
     * 
     * @type {string}
     * @memberof PlaylistItemReadDto
     */
    trackId?: string;
    /**
     * 
     * @type {number}
     * @memberof PlaylistItemReadDto
     */
    index?: number;
    /**
     * 
     * @type {number}
     * @memberof PlaylistItemReadDto
     */
    timesPlayed?: number;
    /**
     * 
     * @type {Date}
     * @memberof PlaylistItemReadDto
     */
    dateAdded?: Date;
}

/**
 * Check if a given object implements the PlaylistItemReadDto interface.
 */
export function instanceOfPlaylistItemReadDto(value: object): boolean {
    return true;
}

export function PlaylistItemReadDtoFromJSON(json: any): PlaylistItemReadDto {
    return PlaylistItemReadDtoFromJSONTyped(json, false);
}

export function PlaylistItemReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaylistItemReadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'trackId': json['trackId'] == null ? undefined : json['trackId'],
        'index': json['index'] == null ? undefined : json['index'],
        'timesPlayed': json['timesPlayed'] == null ? undefined : json['timesPlayed'],
        'dateAdded': json['dateAdded'] == null ? undefined : (new Date(json['dateAdded'])),
    };
}

export function PlaylistItemReadDtoToJSON(value?: PlaylistItemReadDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'trackId': value['trackId'],
        'index': value['index'],
        'timesPlayed': value['timesPlayed'],
        'dateAdded': value['dateAdded'] == null ? undefined : ((value['dateAdded']).toISOString()),
    };
}

