/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrackReadDto } from './TrackReadDto';
import {
    TrackReadDtoFromJSON,
    TrackReadDtoFromJSONTyped,
    TrackReadDtoToJSON,
} from './TrackReadDto';

/**
 * 
 * @export
 * @interface TrackRandomResult
 */
export interface TrackRandomResult {
    /**
     * 
     * @type {Array<TrackReadDto>}
     * @memberof TrackRandomResult
     */
    tracks?: Array<TrackReadDto>;
    /**
     * 
     * @type {number}
     * @memberof TrackRandomResult
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof TrackRandomResult
     */
    total?: number;
    /**
     * 
     * @type {string}
     * @memberof TrackRandomResult
     */
    seed?: string;
}

/**
 * Check if a given object implements the TrackRandomResult interface.
 */
export function instanceOfTrackRandomResult(value: object): boolean {
    return true;
}

export function TrackRandomResultFromJSON(json: any): TrackRandomResult {
    return TrackRandomResultFromJSONTyped(json, false);
}

export function TrackRandomResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackRandomResult {
    if (json == null) {
        return json;
    }
    return {
        
        'tracks': json['tracks'] == null ? undefined : ((json['tracks'] as Array<any>).map(TrackReadDtoFromJSON)),
        'count': json['count'] == null ? undefined : json['count'],
        'total': json['total'] == null ? undefined : json['total'],
        'seed': json['seed'] == null ? undefined : json['seed'],
    };
}

export function TrackRandomResultToJSON(value?: TrackRandomResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tracks': value['tracks'] == null ? undefined : ((value['tracks'] as Array<any>).map(TrackReadDtoToJSON)),
        'count': value['count'],
        'total': value['total'],
        'seed': value['seed'],
    };
}

