/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrackReadDto } from './TrackReadDto';
import {
    TrackReadDtoFromJSON,
    TrackReadDtoFromJSONTyped,
    TrackReadDtoToJSON,
} from './TrackReadDto';

/**
 * 
 * @export
 * @interface TrackGetMultipleResp
 */
export interface TrackGetMultipleResp {
    /**
     * 
     * @type {Array<TrackReadDto>}
     * @memberof TrackGetMultipleResp
     */
    tracks?: Array<TrackReadDto>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TrackGetMultipleResp
     */
    notFound?: Array<string>;
}

/**
 * Check if a given object implements the TrackGetMultipleResp interface.
 */
export function instanceOfTrackGetMultipleResp(value: object): boolean {
    return true;
}

export function TrackGetMultipleRespFromJSON(json: any): TrackGetMultipleResp {
    return TrackGetMultipleRespFromJSONTyped(json, false);
}

export function TrackGetMultipleRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackGetMultipleResp {
    if (json == null) {
        return json;
    }
    return {
        
        'tracks': json['tracks'] == null ? undefined : ((json['tracks'] as Array<any>).map(TrackReadDtoFromJSON)),
        'notFound': json['notFound'] == null ? undefined : json['notFound'],
    };
}

export function TrackGetMultipleRespToJSON(value?: TrackGetMultipleResp | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tracks': value['tracks'] == null ? undefined : ((value['tracks'] as Array<any>).map(TrackReadDtoToJSON)),
        'notFound': value['notFound'],
    };
}

