/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TrackStratificationMode = {
    None: 'None',
    Album: 'Album',
    Circle: 'Circle'
} as const;
export type TrackStratificationMode = typeof TrackStratificationMode[keyof typeof TrackStratificationMode];


export function TrackStratificationModeFromJSON(json: any): TrackStratificationMode {
    return TrackStratificationModeFromJSONTyped(json, false);
}

export function TrackStratificationModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackStratificationMode {
    return json as TrackStratificationMode;
}

export function TrackStratificationModeToJSON(value?: TrackStratificationMode | null): any {
    return value as any;
}

