/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileWriteDto
 */
export interface UserProfileWriteDto {
    /**
     * 
     * @type {string}
     * @memberof UserProfileWriteDto
     */
    displayName: string;
}

/**
 * Check if a given object implements the UserProfileWriteDto interface.
 */
export function instanceOfUserProfileWriteDto(value: object): boolean {
    if (!('displayName' in value)) return false;
    return true;
}

export function UserProfileWriteDtoFromJSON(json: any): UserProfileWriteDto {
    return UserProfileWriteDtoFromJSONTyped(json, false);
}

export function UserProfileWriteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileWriteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'],
    };
}

export function UserProfileWriteDtoToJSON(value?: UserProfileWriteDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'displayName': value['displayName'],
    };
}

