# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
        
      - uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: Install all dependencies
        run: npm install
        
      - name: Install Quasar
        run: npm i -g @quasar/cli
        
      - name: Build
        run: quasar build -d
        
      - name: Copy
        run: copy index.html 404.html
        
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: pages # The branch name where you want to push the assets
          FOLDER: dist/spa # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
